# Generated by Django 5.0.6 on 2024-07-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='details',
            new_name='prescription_text',
        ),
    ]
